---
# tasks file for apache
#
- name: Install http
  yum:
    name: httpd
    state: installed


- name: Start httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: Copy web site
  copy:
    content: "Demo Ansible"
    dest: /var/www/html/index.html
    owner: apache
    group: apache



